extends Node

signal ship_spawned(ship)
signal ship_destroyed(ship)
signal ship_damaged(ship, amount: float, damage_info)
signal projectile_fired(projectile)
signal projectile_water_impact(position: Vector3, strength: float)
signal torpedo_fired(torpedo)
signal torpedo_hit(torpedo, target_ship, result)
signal flooding_started(ship, duration_seconds: float)
signal flooding_ended(ship)
signal battle_started(stage_id: String)
signal battle_cleared(stage_id: String)
signal battle_failed(stage_id: String)
signal wave_started(wave_index: int)
signal game_mode_changed(previous_mode: int, current_mode: int)
signal run_started(stage_id: String)
signal run_updated(run_state: Dictionary)
signal run_finished(result: Dictionary)
signal reward_selected(reward_id: String)
