extends RefCounted
class_name DiveBombReleaseBlockReason

enum Type {
	NONE,
	TOO_EARLY,
	HEADING_NOT_ALIGNED,
	IMPACT_SOLUTION_INVALID,
	SAFETY_ALTITUDE_REACHED,
	NO_AMMUNITION,
	WEAPON_DISABLED,
	AIRCRAFT_DESTROYED,
	CANCELLED,
	MOVEMENT_OWNERSHIP_LOST,
	RELEASE_RETRY_EXHAUSTED,
	ALIGNMENT_TIMEOUT,
}
